name: dhy_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Widened SDK range to ensure compatibility with 3.22.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8    # Updated to latest stable
  hooks_riverpod: ^2.5.1     # Updated to latest stable
  flutter_hooks: ^0.20.5     # Updated to latest stable
  shared_preferences: ^2.2.3 # Stable version compatible with Flutter 3.22
  retrofit: ^4.1.0          # Adjusted to stable version
  flutter_dotenv: ^5.1.0     # Stable version
  auto_route: ^8.1.3         # Adjusted to stable version compatible with Flutter 3.22
  google_fonts: ^6.2.1       # Current version is fine
  flutter_animate: ^4.5.0    # Stable version
  cached_network_image: ^3.3.1 # Stable version
  equatable: ^2.0.5         # Stable version
  flutter_svg: ^2.0.10+1     # Updated to latest stable
  enum_to_string: ^2.0.1     # Stable version

dev_dependencies:
  auto_route_generator: ^8.0.0  # Aligned with auto_route version
  build_runner: ^2.4.11        # Current version is fine
  flutter_lints: ^4.0.0        # Current version is fine
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0   # Aligned with retrofit version

flutter:
  uses-material-design: true
  
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
        - asset: assets/fonts/Exo-Medium.ttf
  
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/fonts/
    - .env.development
    - .env.production